#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: blog/teddy-bear-toss
#+HUGO_FRONT_MATTER_FORMAT: yaml
#+HUGO_TAGS: hockey
#+TITLE: A Question Regarding Teddy Bear Tosses
#+DATE: 2024-01-11
#+DESCRIPTION: Suppose they held a Teddy Bear Toss and no one scored.

* A Question Regarding Teddy Bear Tosses
:PROPERTIES:
:EXPORT_FILE_NAME: index
:END:
Typically, minor league hockey teams have a "Teddy Bear Toss" night at some point close to the holidays, the idea being the team donates the stuffed animals to local charities. At a "Teddy Bear Toss" night, when the home side scores their first goal, fans celebrate in part by throwing the stuffed animals onto the ice.

I've always wondered, what happens if the home team gets shutout? Surely they're getting those teddy bears, right?

Well, I'm not sure how *all* teams do it, but [[https://www.hersheybears.com/news/all-the-faqs-for-our-2024-giant-teddy-bear-toss-on-jan-7/][here's what the Hershey Bears do in the event of a scoreless game]]:

#+begin_quote
*What happens if the Bears have not scored a goal during the GIANT Teddy Bear Toss?*

The Bears are having a great season and we're fully planning on them scoring a goal that will send thousands of teddy bears flying! However, if Hershey has not scored a goal *by the end of the second period*, the GIANT Teddy Bear Toss will occur *during the second intermission*. Instructions on how to proceed will be announced in the arena.
#+end_quote

Now I know, now you know.
